version: "3"

networks:
  internal: {}

services:

  db:
    image: postgres
    restart: always
    env_file:
      - ./envs/.env-db
    networks:
      - internal
    healthcheck:
      test: "exit 0"

  django_image_api:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: PLEASE_CHANGE_THIS_SECRET_TO_SOMETHING_UNIQUE
    env_file:
      - ./envs/.env-backend
    command: sh start_server.sh
    volumes:
      - /var/image_uploader/images:/var/media
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.cleanup-cache.schedule: "@every 30m"
      ofelia.job-exec.cleanup-cache.command: 'sh -c "python manage.py cleantempcache'
      ofelia.job-exec.cleanup-images.schedule: "@daily"
      ofelia.job-exec.cleanup-images.command: 'sh -c "python manage.py cleanimages'
      ofelia.job-exec.cleanup-expired.schedule: "@daily"
      ofelia.job-exec.cleanup-expired.command: 'sh -c "python manage.py cleanexpired'
    healthcheck:
      test: "exit 0"


  cleanup_worker:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    depends_on:
      - django_image_api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
