version: "3"



services:
  django_image_api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=HexOceanTask.settings
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
