# Generated by Django 4.1.6 on 2023-02-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
