# Generated by Django 4.1.6 on 2023-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(default='image/*', max_length=50),
        ),
    ]
