# Generated by Django 4.1.6 on 2023-02-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_image_uuid', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='images.image')),
            ],
        ),
    ]
