# Generated by Django 4.1.6 on 2023-02-16 21:09

from django.db import migrations, models
import django.db.models.deletion
import images.utils
import tiers.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_tier_can_access_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesize',
            name='width',
        ),
        migrations.AlterField(
            model_name='imagesize',
            name='height',
            field=models.IntegerField(default=0, help_text='Must be above 0px', validators=[images.utils.is_above_zero]),
        ),
        migrations.AlterField(
            model_name='userintier',
            name='tier',
            field=models.OneToOneField(default=tiers.models.get_basic_tier, on_delete=django.db.models.deletion.CASCADE, to='tiers.tier'),
        ),
    ]
